from __future__ import annotations

from enum import Enum

from core.events.event_types import (
    EVENT_AUDIO_ALERT,
    EVENT_BOOK,
    EVENT_BROWSER_ACTIVITY,
    EVENT_CAMERA_COVERED,
    EVENT_CAMERA_FROZEN,
    EVENT_CLIPBOARD_ACCESS,
    EVENT_DEVTOOLS_OPENED,
    EVENT_FACE_MISSING,
    EVENT_FULLSCREEN_EXIT,
    EVENT_GAZE_AWAY,
    EVENT_KEYBOARD_SHORTCUT,
    EVENT_LOOK_AWAY,
    EVENT_LOW_LIGHT,
    EVENT_LAPTOP,
    EVENT_MULTI_FACE,
    EVENT_PHONE,
    EVENT_TAB_SWITCH,
)


class StrictnessMode(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


BASE_POINTS = {
    EVENT_FACE_MISSING: 8,
    EVENT_MULTI_FACE: 15,
    EVENT_LOOK_AWAY: 6,
    EVENT_GAZE_AWAY: 6,
    EVENT_PHONE: 20,
    EVENT_BOOK: 14,
    EVENT_LAPTOP: 16,
    EVENT_TAB_SWITCH: 8,
    EVENT_KEYBOARD_SHORTCUT: 5,
    EVENT_CLIPBOARD_ACCESS: 5,
    EVENT_DEVTOOLS_OPENED: 15,
    EVENT_FULLSCREEN_EXIT: 8,
    EVENT_AUDIO_ALERT: 8,
    EVENT_CAMERA_COVERED: 10,
    EVENT_CAMERA_FROZEN: 10,
    EVENT_LOW_LIGHT: 4,
    EVENT_BROWSER_ACTIVITY: 5,
}
