export const API_BASE_URL =
  (import.meta.env.VITE_API_BASE_URL as string | undefined) ?? "http://127.0.0.1:5051";

export const VIDEO_BASE_URL =
  (import.meta.env.VITE_VIDEO_BASE_URL as string | undefined) ?? "http://127.0.0.1:5050";

export const endpoints = {
  health: "/health",
  login: "/auth/login",
  register: "/auth/register",
  me: "/auth/me",
  logout: "/auth/logout",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  googleStart: "/auth/google/start",
  exams: "/exams",
  exam: (id: string) => `/exams/${id}`,
  examPublish: (id: string) => `/exams/${id}/publish`,
  examQuestions: (id: string) => `/exams/${id}/questions`,
  examQuestion: (examId: string, questionId: string) => `/exams/${examId}/questions/${questionId}`,
  questionOptions: (questionId: string) => `/questions/${questionId}/options`,
  questionOption: (questionId: string, optionId: string) => `/questions/${questionId}/options/${optionId}`,
  examAssignments: (id: string) => `/exams/${id}/assignments`,
  examAssignment: (examId: string, assignmentId: string) => `/exams/${examId}/assignments/${assignmentId}`,
  examAttendance: (id: string) => `/exams/${id}/attendance`,
  examAttempts: (id: string) => `/exams/${id}/attempts`,
  studentExams: "/student/exams",
  studentExamJoinCode: "/student/exams/join-code",
  attemptsStart: "/attempts/start",
  attempt: (id: string) => `/attempts/${id}`,
  attemptResponses: (id: string) => `/attempts/${id}/responses`,
  attemptSubmit: (id: string) => `/attempts/${id}/submit`,
  dashboardStudent: "/dashboard/student",
  dashboardInstructor: "/dashboard/instructor",
  dashboardAdmin: "/dashboard/admin",
  settings: "/settings",
  tenants: "/tenants",
  tenant: (id: string) => `/tenants/${id}`,
  auditLogs: "/audit-logs",
  adminUsers: "/admin/users",
  adminUser: (id: string) => `/admin/users/${id}`,
  adminUserPassword: (id: string) => `/admin/users/${id}/password`,
  evidenceCreate: "/evidence",
  browserGuardActive: "/browser-guard/active",
  browserGuardPing: "/browser-guard/ping",
  browserGuardToken: "/browser-guard/token",
  proctorStart: "/proctor/start",
  proctorStop: "/proctor/stop",
  proctorStatus: "/proctor/status",
  tabEvent: "/tab-event",
  keyboardEvent: "/keyboard-event",
  clipboardEvent: "/clipboard-event",
  devtoolsEvent: "/devtools-event",
  fullscreenEvent: "/fullscreen-event",
  sessionsStart: "/sessions/start",
  sessions: "/sessions",
  session: (id: string) => `/sessions/${id}`,
  sessionEnd: (id: string) => `/sessions/${id}/end`,
  sessionEvents: (id: string) => `/sessions/${id}/events`,
  sessionRisk: (id: string) => `/sessions/${id}/risk`,
  sessionRiskTrend: (id: string) => `/sessions/${id}/risk-trend`,
  sessionEvidence: (id: string) => `/sessions/${id}/evidence`,
  sessionBrowserActivity: (id: string) => `/sessions/${id}/browser-activity`,
  sessionAudio: (id: string) => `/sessions/${id}/audio`,
  sessionReport: (id: string) => `/sessions/${id}/report`,
  sessionReportDownload: (id: string) => `/sessions/${id}/report/download`,
  sessionReview: (id: string) => `/sessions/${id}/review`,
  assistantQuery: "/assistant/query",
  reportsGenerate: "/reports/generate",
  cameraStream: (_id: string, source: "primary" | "secondary" = "primary") =>
    source === "primary" ? "/video_feed" : "/video_feed_secondary",
} as const;
