/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomScanRouteImport } from './routes/room-scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as IdVerificationRouteImport } from './routes/id-verification'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as BrowserGuardRouteImport } from './routes/browser-guard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomScanRoute = RoomScanRouteImport.update({
  id: '/room-scan',
  path: '/room-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const IdVerificationRoute = IdVerificationRouteImport.update({
  id: '/id-verification',
  path: '/id-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserGuardRoute = BrowserGuardRouteImport.update({
  id: '/browser-guard',
  path: '/browser-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/browser-guard': typeof BrowserGuardRoute
  '/checklist': typeof ChecklistRoute
  '/exam': typeof ExamRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/id-verification': typeof IdVerificationRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room-scan': typeof RoomScanRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/browser-guard': typeof BrowserGuardRoute
  '/checklist': typeof ChecklistRoute
  '/exam': typeof ExamRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/id-verification': typeof IdVerificationRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room-scan': typeof RoomScanRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/browser-guard': typeof BrowserGuardRoute
  '/checklist': typeof ChecklistRoute
  '/exam': typeof ExamRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/id-verification': typeof IdVerificationRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room-scan': typeof RoomScanRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/browser-guard'
    | '/checklist'
    | '/exam'
    | '/forgot-password'
    | '/id-verification'
    | '/instructor'
    | '/login'
    | '/monitor'
    | '/oauth-callback'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/room-scan'
    | '/settings'
    | '/setup'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/browser-guard'
    | '/checklist'
    | '/exam'
    | '/forgot-password'
    | '/id-verification'
    | '/instructor'
    | '/login'
    | '/monitor'
    | '/oauth-callback'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/room-scan'
    | '/settings'
    | '/setup'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/browser-guard'
    | '/checklist'
    | '/exam'
    | '/forgot-password'
    | '/id-verification'
    | '/instructor'
    | '/login'
    | '/monitor'
    | '/oauth-callback'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/room-scan'
    | '/settings'
    | '/setup'
    | '/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  BrowserGuardRoute: typeof BrowserGuardRoute
  ChecklistRoute: typeof ChecklistRoute
  ExamRoute: typeof ExamRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IdVerificationRoute: typeof IdVerificationRoute
  InstructorRoute: typeof InstructorRoute
  LoginRoute: typeof LoginRoute
  MonitorRoute: typeof MonitorRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomScanRoute: typeof RoomScanRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-scan': {
      id: '/room-scan'
      path: '/room-scan'
      fullPath: '/room-scan'
      preLoaderRoute: typeof RoomScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-verification': {
      id: '/id-verification'
      path: '/id-verification'
      fullPath: '/id-verification'
      preLoaderRoute: typeof IdVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser-guard': {
      id: '/browser-guard'
      path: '/browser-guard'
      fullPath: '/browser-guard'
      preLoaderRoute: typeof BrowserGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  BrowserGuardRoute: BrowserGuardRoute,
  ChecklistRoute: ChecklistRoute,
  ExamRoute: ExamRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IdVerificationRoute: IdVerificationRoute,
  InstructorRoute: InstructorRoute,
  LoginRoute: LoginRoute,
  MonitorRoute: MonitorRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomScanRoute: RoomScanRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
