EVENT_FACE_MISSING = "Face Missing"
EVENT_MULTI_FACE = "Multiple Faces"
EVENT_LOOK_AWAY = "Looking Away"
EVENT_GAZE_AWAY = "Gaze Away"
EVENT_PHONE = "Phone Detected"
EVENT_BOOK = "Book Detected"
EVENT_LAPTOP = "Laptop Detected"
EVENT_TAB_SWITCH = "Tab Switch"
EVENT_KEYBOARD_SHORTCUT = "Keyboard Shortcut"
EVENT_CLIPBOARD_ACCESS = "Clipboard Access"
EVENT_DEVTOOLS_OPENED = "DevTools Opened"
EVENT_FULLSCREEN_EXIT = "Fullscreen Exit"
EVENT_AUDIO_ALERT = "Audio Alert"
EVENT_CAMERA_COVERED = "Camera Covered"
EVENT_CAMERA_FROZEN = "Camera Frozen"
EVENT_LOW_LIGHT = "Low Light"
EVENT_BROWSER_ACTIVITY = "Browser Activity"

VISION_EVENT_TYPES = [
    EVENT_FACE_MISSING,
    EVENT_MULTI_FACE,
    EVENT_LOOK_AWAY,
    EVENT_GAZE_AWAY,
    EVENT_PHONE,
    EVENT_BOOK,
    EVENT_LAPTOP,
    EVENT_CAMERA_COVERED,
    EVENT_CAMERA_FROZEN,
    EVENT_LOW_LIGHT,
]

ALL_EVENT_TYPES = [
    *VISION_EVENT_TYPES,
    EVENT_TAB_SWITCH,
    EVENT_KEYBOARD_SHORTCUT,
    EVENT_CLIPBOARD_ACCESS,
    EVENT_DEVTOOLS_OPENED,
    EVENT_FULLSCREEN_EXIT,
    EVENT_AUDIO_ALERT,
    EVENT_BROWSER_ACTIVITY,
]

EVENT_ICONS = {
    EVENT_FACE_MISSING: "face",
    EVENT_MULTI_FACE: "users",
    EVENT_LOOK_AWAY: "eye-off",
    EVENT_GAZE_AWAY: "eye",
    EVENT_PHONE: "phone",
    EVENT_BOOK: "book",
    EVENT_LAPTOP: "laptop",
    EVENT_TAB_SWITCH: "globe",
    EVENT_KEYBOARD_SHORTCUT: "keyboard",
    EVENT_CLIPBOARD_ACCESS: "clipboard",
    EVENT_DEVTOOLS_OPENED: "terminal",
    EVENT_FULLSCREEN_EXIT: "minimize",
    EVENT_AUDIO_ALERT: "mic",
    EVENT_CAMERA_COVERED: "camera-off",
    EVENT_CAMERA_FROZEN: "pause",
    EVENT_LOW_LIGHT: "moon",
    EVENT_BROWSER_ACTIVITY: "browser",
}

EVENT_COLORS = {
    EVENT_FACE_MISSING: "#ef4444",
    EVENT_MULTI_FACE: "#dc2626",
    EVENT_LOOK_AWAY: "#f59e0b",
    EVENT_GAZE_AWAY: "#f97316",
    EVENT_PHONE: "#b91c1c",
    EVENT_BOOK: "#ea580c",
    EVENT_LAPTOP: "#c2410c",
    EVENT_TAB_SWITCH: "#6366f1",
    EVENT_KEYBOARD_SHORTCUT: "#8b5cf6",
    EVENT_CLIPBOARD_ACCESS: "#a855f7",
    EVENT_DEVTOOLS_OPENED: "#7c3aed",
    EVENT_FULLSCREEN_EXIT: "#0ea5e9",
    EVENT_AUDIO_ALERT: "#14b8a6",
    EVENT_CAMERA_COVERED: "#64748b",
    EVENT_CAMERA_FROZEN: "#475569",
    EVENT_LOW_LIGHT: "#334155",
    EVENT_BROWSER_ACTIVITY: "#2563eb",
}

RISK_LOW = "Low"
RISK_MEDIUM = "Moderate"
RISK_HIGH = "Suspicious"
RISK_CRITICAL = "Critical"

DIR_FORWARD = "forward"
DIR_LEFT = "left"
DIR_RIGHT = "right"
DIR_DOWN = "down"
DIR_UP = "up"

TABLE_STUDENTS = "Students"
TABLE_EVENTS = "Events"
TABLE_SESSIONS = "Sessions"
